# Generated by Django 5.1 on 2024-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='강의명')),
                ('description', models.CharField(max_length=1000, verbose_name='추천 이유')),
            ],
            options={
                'verbose_name': '강의',
                'db_table': 'lecture',
            },
        ),
    ]
