# Generated by Django 5.1 on 2024-12-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='code',
            field=models.CharField(default=None, max_length=10, verbose_name='과목 코드'),
            preserve_default=False,
        ),
    ]
